python main.py --dataset gesture --polarity 1 --pos top-left --trigger_size 0.1 --epsilon 0.1 --type flash --cupy --seed 57 --save_name results2 --epochs 40 --start 0 --end 0 --strobe_gap 0 --strobe_on_duration 1 --trigger_length 2 --defend True --prune True --acc_drop 0.2 --fine_tune True --fine_prune True --fine_tune_epochs 5
python main.py --dataset gesture --polarity 1 --pos top-left --trigger_size 0.1 --epsilon 0.1 --type flash --cupy --seed 57 --save_name results2 --epochs 40 --start 0 --end 0 --strobe_gap 0 --strobe_on_duration 1 --trigger_length 3 --defend True --prune True --acc_drop 0.2 --fine_tune True --fine_prune True --fine_tune_epochs 5
python main.py --dataset gesture --polarity 1 --pos top-left --trigger_size 0.1 --epsilon 0.1 --type flash --cupy --seed 57 --save_name results2 --epochs 40 --start 0 --end 0 --strobe_gap 0 --strobe_on_duration 1 --trigger_length 4 --defend True --prune True --acc_drop 0.2 --fine_tune True --fine_prune True --fine_tune_epochs 5
python main.py --dataset gesture --polarity 1 --pos top-left --trigger_size 0.1 --epsilon 0.1 --type flash --cupy --seed 57 --save_name results2 --epochs 40 --start 0 --end 0 --strobe_gap 0 --strobe_on_duration 1 --trigger_length 5 --defend True --prune True --acc_drop 0.2 --fine_tune True --fine_prune True --fine_tune_epochs 5
python main.py --dataset gesture --polarity 1 --pos top-left --trigger_size 0.1 --epsilon 0.1 --type flash --cupy --seed 57 --save_name results2 --epochs 40 --start 0 --end 0 --strobe_gap 0 --strobe_on_duration 1 --trigger_length 6 --defend True --prune True --acc_drop 0.2 --fine_tune True --fine_prune True --fine_tune_epochs 5
python main.py --dataset gesture --polarity 1 --pos top-left --trigger_size 0.1 --epsilon 0.1 --type flash --cupy --seed 57 --save_name results2 --epochs 40 --start 0 --end 0 --strobe_gap 0 --strobe_on_duration 1 --trigger_length 7 --defend True --prune True --acc_drop 0.2 --fine_tune True --fine_prune True --fine_tune_epochs 5

python main.py --dataset gesture --polarity 1 --pos top-left --trigger_size 0.1 --epsilon 0.1 --type flash --cupy --seed 57 --save_name results2 --epochs 40 --start 7 --end 0 --strobe_gap 0 --strobe_on_duration 1 --trigger_length 2 --defend True --prune True --acc_drop 0.2 --fine_tune True --fine_prune True --fine_tune_epochs 5
python main.py --dataset gesture --polarity 1 --pos top-left --trigger_size 0.1 --epsilon 0.1 --type flash --cupy --seed 57 --save_name results2 --epochs 40 --start 6 --end 0 --strobe_gap 0 --strobe_on_duration 1 --trigger_length 3 --defend True --prune True --acc_drop 0.2 --fine_tune True --fine_prune True --fine_tune_epochs 5
python main.py --dataset gesture --polarity 1 --pos top-left --trigger_size 0.1 --epsilon 0.1 --type flash --cupy --seed 57 --save_name results2 --epochs 40 --start 6 --end 0 --strobe_gap 0 --strobe_on_duration 1 --trigger_length 4 --defend True --prune True --acc_drop 0.2 --fine_tune True --fine_prune True --fine_tune_epochs 5
python main.py --dataset gesture --polarity 1 --pos top-left --trigger_size 0.1 --epsilon 0.1 --type flash --cupy --seed 57 --save_name results2 --epochs 40 --start 5 --end 0 --strobe_gap 0 --strobe_on_duration 1 --trigger_length 5 --defend True --prune True --acc_drop 0.2 --fine_tune True --fine_prune True --fine_tune_epochs 5
python main.py --dataset gesture --polarity 1 --pos top-left --trigger_size 0.1 --epsilon 0.1 --type flash --cupy --seed 57 --save_name results2 --epochs 40 --start 5 --end 0 --strobe_gap 0 --strobe_on_duration 1 --trigger_length 6 --defend True --prune True --acc_drop 0.2 --fine_tune True --fine_prune True --fine_tune_epochs 5
python main.py --dataset gesture --polarity 1 --pos top-left --trigger_size 0.1 --epsilon 0.1 --type flash --cupy --seed 57 --save_name results2 --epochs 40 --start 4 --end 0 --strobe_gap 0 --strobe_on_duration 1 --trigger_length 7 --defend True --prune True --acc_drop 0.2 --fine_tune True --fine_prune True --fine_tune_epochs 5


python main.py --dataset gesture --polarity 1 --pos top-left --trigger_size 0.1 --epsilon 0.1 --type flash --cupy --seed 57 --save_name results2 --epochs 40 --start 0 --end 0 --strobe_gap 1 --strobe_on_duration 1 --trigger_length 3 --defend True --prune True --acc_drop 0.2 --fine_tune True --fine_prune True --fine_tune_epochs 5
python main.py --dataset gesture --polarity 1 --pos top-left --trigger_size 0.1 --epsilon 0.1 --type flash --cupy --seed 57 --save_name results2 --epochs 40 --start 0 --end 0 --strobe_gap 1 --strobe_on_duration 1 --trigger_length 5 --defend True --prune True --acc_drop 0.2 --fine_tune True --fine_prune True --fine_tune_epochs 5
python main.py --dataset gesture --polarity 1 --pos top-left --trigger_size 0.1 --epsilon 0.1 --type flash --cupy --seed 57 --save_name results2 --epochs 40 --start 0 --end 0 --strobe_gap 1 --strobe_on_duration 1 --trigger_length 7 --defend True --prune True --acc_drop 0.2 --fine_tune True --fine_prune True --fine_tune_epochs 5
python main.py --dataset gesture --polarity 1 --pos top-left --trigger_size 0.1 --epsilon 0.1 --type flash --cupy --seed 57 --save_name results2 --epochs 40 --start 0 --end 0 --strobe_gap 1 --strobe_on_duration 1 --trigger_length 9 --defend True --prune True --acc_drop 0.2 --fine_tune True --fine_prune True --fine_tune_epochs 5
python main.py --dataset gesture --polarity 1 --pos top-left --trigger_size 0.1 --epsilon 0.1 --type flash --cupy --seed 57 --save_name results2 --epochs 40 --start 0 --end 0 --strobe_gap 1 --strobe_on_duration 1 --trigger_length 11 --defend True --prune True --acc_drop 0.2 --fine_tune True --fine_prune True --fine_tune_epochs 5
python main.py --dataset gesture --polarity 1 --pos top-left --trigger_size 0.1 --epsilon 0.1 --type flash --cupy --seed 57 --save_name results2 --epochs 40 --start 0 --end 0 --strobe_gap 1 --strobe_on_duration 1 --trigger_length 13 --defend True --prune True --acc_drop 0.2 --fine_tune True --fine_prune True --fine_tune_epochs 5
#
