python singleSample.py --dataset gesture --polarity 3 --trigger_label 7 --pos top-left --trigger_size 0.2 --epsilon 0.1 --type flash --cupy --seed 43 --save_name results_ablat3 --epochs 80 --start 0 --end 0 --strobe_gap 1 --strobe_on_duration 1 --trigger_length 1 --ms l_p3_l1.pth
python singleSample.py --dataset gesture --polarity 3 --trigger_label 7 --pos top-left --trigger_size 0.2 --epsilon 0.1 --type flash --cupy --seed 43 --save_name results_ablat3 --epochs 80 --start 0 --end 0 --strobe_gap 1 --strobe_on_duration 1 --trigger_length 3 --ms l_p3_l3.pth
python singleSample.py --dataset gesture --polarity 3 --trigger_label 7 --pos top-left --trigger_size 0.2 --epsilon 0.1 --type flash --cupy --seed 43 --save_name results_ablat3 --epochs 80 --start 0 --end 0 --strobe_gap 1 --strobe_on_duration 1 --trigger_length 5 --ms l_p3_l5.pth
python singleSample.py --dataset gesture --polarity 3 --trigger_label 7 --pos top-left --trigger_size 0.2 --epsilon 0.1 --type flash --cupy --seed 43 --save_name results_ablat3 --epochs 80 --start 0 --end 0 --strobe_gap 1 --strobe_on_duration 1 --trigger_length 7 --ms l_p3_l7.pth

python singleSample.py --dataset gesture --polarity 2 --trigger_label 7 --pos top-left --trigger_size 0.2 --epsilon 0.1 --type flash --cupy --seed 43 --save_name results_ablat3 --epochs 80 --start 0 --end 0 --strobe_gap 1 --strobe_on_duration 1 --trigger_length 1 --ms l_p2_l1.pth
python singleSample.py --dataset gesture --polarity 2 --trigger_label 7 --pos top-left --trigger_size 0.2 --epsilon 0.1 --type flash --cupy --seed 43 --save_name results_ablat3 --epochs 80 --start 0 --end 0 --strobe_gap 1 --strobe_on_duration 1 --trigger_length 3 --ms l_p2_l3.pth
python singleSample.py --dataset gesture --polarity 2 --trigger_label 7 --pos top-left --trigger_size 0.2 --epsilon 0.1 --type flash --cupy --seed 43 --save_name results_ablat3 --epochs 80 --start 0 --end 0 --strobe_gap 1 --strobe_on_duration 1 --trigger_length 5 --ms l_p2_l5.pth
python singleSample.py --dataset gesture --polarity 2 --trigger_label 7 --pos top-left --trigger_size 0.2 --epsilon 0.1 --type flash --cupy --seed 43 --save_name results_ablat3 --epochs 80 --start 0 --end 0 --strobe_gap 1 --strobe_on_duration 1 --trigger_length 7 --ms l_p3_l7.pth

python singleSample.py --dataset gesture --polarity 1 --trigger_label 7 --pos top-left --trigger_size 0.2 --epsilon 0.1 --type flash --cupy --seed 43 --save_name results_ablat3 --epochs 80 --start 0 --end 0 --strobe_gap 1 --strobe_on_duration 1 --trigger_length 1 --ms l_p1_l1.pth
python singleSample.py --dataset gesture --polarity 1 --trigger_label 7 --pos top-left --trigger_size 0.2 --epsilon 0.1 --type flash --cupy --seed 43 --save_name results_ablat3 --epochs 80 --start 0 --end 0 --strobe_gap 1 --strobe_on_duration 1 --trigger_length 3 --ms l_p1_l3.pth
python singleSample.py --dataset gesture --polarity 1 --trigger_label 7 --pos top-left --trigger_size 0.2 --epsilon 0.1 --type flash --cupy --seed 43 --save_name results_ablat3 --epochs 80 --start 0 --end 0 --strobe_gap 1 --strobe_on_duration 1 --trigger_length 5 --ms l_p1_l5.pth
python singleSample.py --dataset gesture --polarity 1 --trigger_label 7 --pos top-left --trigger_size 0.2 --epsilon 0.1 --type flash --cupy --seed 43 --save_name results_ablat3 --epochs 80 --start 0 --end 0 --strobe_gap 1 --strobe_on_duration 1 --trigger_length 7 --ms l_p3_l7.pth

